apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: myapp
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: studentdb
  init.sql: |
    CREATE TABLE IF NOT EXISTS students (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      age INT NOT NULL
    );
  config.js: |
    window._env_ = {
      API_URL: "http://192.168.30.45:30081"
    };
