apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      #targetPort: 3000
      #nodePort: {{ .Values.backend.service.nodePort }}
  type: ClusterIP

