apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.backend.service.nodePort }}
  type: NodePort

