apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.mysql.auth.username | b64enc | quote }}
  password: {{ .Values.mysql.auth.password | b64enc | quote }}

